name: aws-access-check
run-name: ${{ github.actor }} is testing aws access with secrets
on: [push]

env:
  AWS_ACCESS_KEY_ID:: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

jobs:
  aws-connection-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - run: aws --version
      - run: echo $AWS_ACCESS_KEY_ID
