name: check for go task
run-name: ${{ github.actor }} is testing for go task in the runner
on: [push]

jobs:
  task-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.15'

      - name: huh
        run: task --version
