name: terraform-validate
run-name: ${{ github.actor }} is testing GitHub Actions
on: [push]
jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: which terraform
      - run: terraform --version
